---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This CloudFormation template creates an infrastructure for 
  deploying a Hugo website to an AWS S3 bucket and pointing a 
  custom domain name to it using AWS Route 53.

Parameters:
  DomainName:
    Type: String
    Description: The domain name of the website.

Resources:
  RjsadowSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        
  RjsadowSiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref RjsadowSiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: "*"
          Action: s3:GetObject
          Resource: !Sub "arn:aws:s3:::${DomainName}/*"

  RjsadowHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName

  RjsadowSiteCloudFrontAliasRecordSet:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref RjsadowHostedZone
      RecordSets:
      - Name: !Ref DomainName
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt [RjsadowSiteCloudFrontDistribution, DomainName]
          EvaluateTargetHealth: true

  RjsadowSiteCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      SubjectAlternativeNames:
        - !Sub "www.${DomainName}"
      Tags:
        - Key: Name
          Value: RjsadowSiteCert

  RjsadowSiteCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        Origins:
          - DomainName: !Select [2, !Split ["/", !GetAtt RjsadowSiteBucket.WebsiteURL]]
            Id: S3Origin
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: http-only
        Enabled: true
        HttpVersion: 'http2'
        DefaultRootObject: index.html
        Aliases:
         - !Ref DomainName
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
          MinTTL: 86400
        ViewerCertificate:
          AcmCertificateArn: !Ref RjsadowSiteCert
          SslSupportMethod: sni-only