name: Deploy Hugo Site to S3 Bucket
on:
  push:
    branches:
      - main

env:
  HUGO_VERSION: '0.88.1'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy CloudFormation Stack
      run: |
        aws cloudformation deploy --stack-name rjsadow-site-stack --template-file infrastructure/aws/cloudformation/site.yml --parameter-overrides DomainName="rjsadow.com"

    - name: Install Hugo
      uses: peaceiris/actions-hugo@v2.6.0
      with:
        hugo-version: ${{ env.HUGO_VERSION }}

    - name: Build Hugo site
      run: hugo --minify

    - name: Deploy Hugo Site to S3 Bucket
      run: |
        aws s3 sync public/ s3://rjsadow.com/